export enum FieldNames {
  CountPerPage = 'countPerPage',
  PageNumber = 'pageNumber',
  TotalRecords = 'totalRecords',
  PageCount = 'pageCount',
  SortOrder = 'sortOrder',
  SortField = 'sortField',
  FilterField = 'filterField',
  FilterValue = 'filterValue',
  Name = 'name',
  Price = 'price',
  Code = 'code',
  Sku = 'sku',
  InStock = 'inStock',
  Description = 'description',
  Images = 'images',
  Attributes = 'attributes',
  Values = 'values',
  Id = 'id',
}
